spring:
  application:
    name: multitenancy

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  tenant:
    default-tenant-id: DS1
    datasources:
    - tenant-id: DS1
      url: jdbc:postgresql://localhost:54321/music
      username: ds1
      password: ds1password    
    
    - tenant-id: DS2
      url: jdbc:postgresql://localhost:54322/music
      username: ds2
      password: ds2password  

logging:
  level:
    root: INFO